version: "1"
rules:                      # Array of rules
  - base: master            # Required. Target branch
    upstream: andreasvc:master    # Required. Must be in the same fork network.
    mergeMethod: merge  
    assignees:              # Optional
      - readevalprint
    reviewers:              # Optional
      - readevalprint
